#!/usr/bin/env Rscript
PROJECT="EUR_SPC_isoform_HRC_23vc"

# Grabbing data from HSQs produced by genes with SNPs in the cis window
temp = unlist(list.files(path=paste("data/", PROJECT, "/output/hsqs", sep=""), pattern="*.hsq"))

hsqs = t(sapply(X=temp, function(file_name) {
                    hsq = read.table(paste('data/', PROJECT, '/output/hsqs/', file_name, sep=''), header=TRUE, nrows=48, fill=TRUE)
                    hsq[47,] = c("V(G)/Vp", hsq[48,1], hsq[48,2])
                    hsq = hsq[-48,]
                    hsq_log = read.table(paste('data/', PROJECT, '/output/hsqs/', file_name, sep=''), header=FALSE, skip=49, fill=TRUE)
                    # Gene ID,
                    # Variance from Chr 1-22,
                    # Residual Variance,
                    # Phenotypic Variance,
                    # Chr 1-22 h2,
                    # SNP h2,
                    # SE Variance from Chr 1-22,
                    # SE Residual Variance,
                    # SE Phenotypic Variance,
                    # SE Chr 1-22 h2,
                    # SE SNP h2,
                    # P-value
                    line = c(substring(file_name, 1, nchar(file_name) - 4), 
                             hsq[1,2], hsq[2,2], hsq[3,2], hsq[4,2], hsq[5,2], hsq[6,2], 
                             hsq[7,2], hsq[8,2], hsq[9,2], hsq[10,2], hsq[11,2], hsq[12,2], 
                             hsq[13,2], hsq[14,2], hsq[15,2], hsq[16,2], hsq[17,2], 
                             hsq[18,2], hsq[19,2], hsq[20,2], hsq[21,2], hsq[22,2], 
                             hsq[23,2], hsq[24,2], hsq[25,2], hsq[26,2], hsq[27,2], 
                             hsq[28,2], hsq[29,2], hsq[30,2], hsq[31,2], hsq[32,2], 
                             hsq[33,2], hsq[34,2], hsq[35,2], hsq[36,2], hsq[37,2], 
                             hsq[38,2], hsq[39,2], hsq[40,2], hsq[41,2], hsq[42,2], 
                             hsq[43,2], hsq[44,2], hsq[45,2], hsq[46,2], hsq[47,2], 
                             hsq[1,3], hsq[2,3], hsq[3,3], hsq[4,3], hsq[5,3], hsq[6,3], 
                             hsq[7,3], hsq[8,3], hsq[9,3], hsq[10,3], hsq[11,3], hsq[12,3], 
                             hsq[13,3], hsq[14,3], hsq[15,3], hsq[16,3], hsq[17,3], 
                             hsq[18,3], hsq[19,3], hsq[20,3], hsq[21,3], hsq[22,3], 
                             hsq[23,3], hsq[24,3], hsq[25,3], hsq[26,3], hsq[27,3], 
                             hsq[28,3], hsq[29,3], hsq[30,3], hsq[31,3], hsq[32,3], 
                             hsq[33,3], hsq[34,3], hsq[35,3], hsq[36,3], hsq[37,3], 
                             hsq[38,3], hsq[39,3], hsq[40,3], hsq[41,3], hsq[42,3], 
                             hsq[43,3], hsq[44,3], hsq[45,3], hsq[46,3], hsq[47,3],
                             hsq_log[5,2]
                    )
                    return(line)
}))

colnames(hsqs) = c("ID",
                   "V_Chr_1",
                   "V_Chr_2",
                   "V_Chr_3",
                   "V_Chr_4",
                   "V_Chr_5",
                   "V_Chr_6",
                   "V_Chr_7",
                   "V_Chr_8",
                   "V_Chr_9",
                   "V_Chr_10",
                   "V_Chr_11",
                   "V_Chr_12",
                   "V_Chr_13",
                   "V_Chr_14",
                   "V_Chr_15",
                   "V_Chr_16",
                   "V_Chr_17",
                   "V_Chr_18",
                   "V_Chr_19",
                   "V_Chr_20",
                   "V_Chr_21",
                   "V_Chr_22",
                   "V_Res",
                   "V_Phe",
                   "Chr_1_h2",
                   "Chr_2_h2",
                   "Chr_3_h2",
                   "Chr_4_h2",
                   "Chr_5_h2",
                   "Chr_6_h2",
                   "Chr_7_h2",
                   "Chr_8_h2",
                   "Chr_9_h2",
                   "Chr_10_h2",
                   "Chr_11_h2",
                   "Chr_12_h2",
                   "Chr_13_h2",
                   "Chr_14_h2",
                   "Chr_15_h2",
                   "Chr_16_h2",
                   "Chr_17_h2",
                   "Chr_18_h2",
                   "Chr_19_h2",
                   "Chr_20_h2",
                   "Chr_21_h2",
                   "Chr_22_h2",
                   "SNP_h2",

                   "SE_V_Chr_1",
                   "SE_V_Chr_2",
                   "SE_V_Chr_3",
                   "SE_V_Chr_4",
                   "SE_V_Chr_5",
                   "SE_V_Chr_6",
                   "SE_V_Chr_7",
                   "SE_V_Chr_8",
                   "SE_V_Chr_9",
                   "SE_V_Chr_10",
                   "SE_V_Chr_11",
                   "SE_V_Chr_12",
                   "SE_V_Chr_13",
                   "SE_V_Chr_14",
                   "SE_V_Chr_15",
                   "SE_V_Chr_16",
                   "SE_V_Chr_17",
                   "SE_V_Chr_18",
                   "SE_V_Chr_19",
                   "SE_V_Chr_20",
                   "SE_V_Chr_21",
                   "SE_V_Chr_22",
                   "SE_V_Res",
                   "SE_V_Phe",
                   "SE_Chr_1_h2",
                   "SE_Chr_2_h2",
                   "SE_Chr_3_h2",
                   "SE_Chr_4_h2",
                   "SE_Chr_5_h2",
                   "SE_Chr_6_h2",
                   "SE_Chr_7_h2",
                   "SE_Chr_8_h2",
                   "SE_Chr_9_h2",
                   "SE_Chr_10_h2",
                   "SE_Chr_11_h2",
                   "SE_Chr_12_h2",
                   "SE_Chr_13_h2",
                   "SE_Chr_14_h2",
                   "SE_Chr_15_h2",
                   "SE_Chr_16_h2",
                   "SE_Chr_17_h2",
                   "SE_Chr_18_h2",
                   "SE_Chr_19_h2",
                   "SE_Chr_20_h2",
                   "SE_Chr_21_h2",
                   "SE_Chr_22_h2",
                   "SE_SNP_h2",
                   "P_val"
)

rownames(hsqs) = hsqs[,"ID"]
hsqs = as.data.frame(hsqs)
for (i in 2:96) {
    hsqs[,i] = as.numeric(hsqs[,i])
}
write.table(hsqs, paste("data/", PROJECT, "/output/results/all_variance.txt", sep=""), quote=FALSE, row.names=FALSE, col.names=TRUE)

